name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: '8.0'

      - name: Install
        run: make setup

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test

      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test
          coverageLocations: ${{github.workplace}}/clover.xml:clover
          debug: true
